version: "3.8"

services:
  magic-engine-test-server:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    restart: unless-stopped
    ports:
      # Map the port 25665 to the default minecraft server port
      - "25665:25565"
      # Voice chat port
      # - "24454:24454/udp"
    environment:
      EULA: "TRUE"
      TYPE: "FORGE"
      FORGE_VERSION: "43.3.0"
      VERSION: "1.19.2"
      MEMORY: 4G
      MAX_MEMORY: 6G
      SERVER_NAME: "Magic Engine Test Server"
      MOTD: "Time to cook"
      ICON: "https://cdn.discordapp.com/emojis/959558350532657212.gif"

      TZ: "Europe/Paris"
      
      #Delete old logs
      ENABLE_ROLLING_LOGS: "true"

      #World name
      LEVEL: "florida"
      #World type
      #LEVEL_TYPE: AMPLIFIED
      
      #Disable spawn protection
      SPAWN_PROTECTION: 0
      #Set default gamemode to creative
      MODE: creative

      #Get the mods from the txt file
      MODS_FILE: /extras/mods.txt
      #Clear old mods
      REMOVE_OLD_MODS: "TRUE"
      REMOVE_OLD_MODS_EXCLUDE: ""

      OVERRIDE_WHITELIST: "true"
      ENABLE_WHITELIST: "true"
      EXISTING_WHITELIST_FILE: MERGE
      WHITELIST: |
        CheeseMcBaguette
        XeonMations
        Willoguns
        LukaszL
        captainatom931
        xXFurryHunter420

      EXISTING_OPS_FILE: MERGE
      OPS: |
        CheeseMcBaguette
        XeonMations
  
    volumes:
    # use a named, managed volume for data volume
    - ./data:/data

    # attach local host directory "mods" in same directory as this compose file
    # all mods in this directory get copied into /data/mods at startup
    # - ./mods:/mods:ro

    # attach local host directory "config" in same directory as this compose file
    # all config files in this directory get copied into /data/config at startup
    - ./config:/config:ro

    # attach the mods.txt file to the /extras/mods.txt path inside /data
    # mods.txt file get copied into /data/extras/mods.txt at startup
    - ./mods.txt:/extras/mods.txt:ro
volumes:
  data: {}
networks:
  localprom:
    driver: bridge